package com.htxapps.horoscopochino;

import android.content.Intent;
import android.graphics.drawable.Drawable;
import android.media.Image;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;

public class Inicio extends AppCompatActivity {

    ImageView Imagen;
    TextView NombreTit,Info,Info2;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_inicio);

        Imagen =  (ImageView) findViewById(R.id.imagenAnimal);
        NombreTit = (TextView) findViewById(R.id.txtNombreTit);
        Info = (TextView) findViewById(R.id.txtInfo);
        Info2 = (TextView) findViewById(R.id.txtInfo2);

        NombreTit.setText((CharSequence) MainActivity.EnSesion.getNombre());


        Intent datos = getIntent();
        Bundle extras = datos.getExtras();
        String Año = (String) extras.get("Año");
        if (Año.equals("1998")|Año.equals("1902")|Año.equals("1914")|Año.equals("1926")|Año.equals("1938")|Año.equals("1950")|Año.equals("1962")|Año.equals("1974")|Año.equals("1986")|Año.equals("2010")|Año.equals("2022"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.tigre));
            Info.setText("Para quienes nacieron bajo la influencia del Tigre, será un mejor año que el anterior, Mono. Sin embargo, no deberán asumir grandes riesgos, sino más bien trabajar y conservar lo que hasta ahora han conseguido. Excelente año para manifestar el costado más artístico y creativo del signo. Dedicar tiempo a explorar nuevas alternativas de expresión será sanador y ayudará a compensar las extensas horas de trabajo que les espera. En el amor comenzará complicado pero mejorará a medida que el año avance. Cuidado con la tendencia a pensar siempre en el futuro y que eso impida trabajar el presente para que las cosas ocurran. Excelentes novedades en torno al hogar y la familia.");
            Info2.setText("El Tigre es el rey de la seducción. Digno y afectuoso, su naturaleza lo hace casi siempre muy atractivo. Carismático y confiado en sí mismo, posee un aire de autoridad que la mayoría encuentra difícil de resistir. Encantador y divertido, aunque nunca pierde de vista o deja de perseguir sus objetivos ni ceder el control. Independiente y audaz, el Tigre representa la libertad y no duda cuando quiere algo. En Oriente se respeta a este extraordinario felino porque según la creencia popular en la casa protege contra la negatividad y las calamidades. Con un destino muy peculiar, a lo largo de su vida le pasarán cosas que tal vez nunca sepa por qué o cómo se generaron, pero las vivirá con gran pasión e intensidad. Representa la libertad, la independencia y rebeldía. No soporta que lo manden y luchará por no sentirse atado. Necesita hacer lo que quiere, posee encanto y tiene mucha facilidad para comunicarse siendo extremadamente sincero y frontal. Inestable emocionalmente, sexy y seductor, no conoce el descanso y su vida está signada por un ritmo que lo mantiene vital y como el Tigre, siempre alerta. El signo análogo al Tigre es Acuario. ");
        }
        if (Año.equals("1997")|Año.equals("1901")|Año.equals("1913")|Año.equals("1925")|Año.equals("1937")|Año.equals("1949")|Año.equals("1961")|Año.equals("1973")|Año.equals("1985")|Año.equals("2009")|Año.equals("2021"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.bufalo));
            Info.setText("El Buey se verá beneficiado este año por la energía afín del Gallo. Ambos son pragmáticos y prefieren no tomar ningún riesgo. Las personas nacidas un año Buey poseen metas claras, se esfuerzan por alcanzarlas y disfrutan de sus logros. Este año se liberarán de viejas ataduras y emprenderán un camino de superación, tanto en lo personal como en el ámbito laboral y material. Será un año muy productivo pero deberán ser más flexibles, de eso modo podrán abrirse a nuevos horizontes y explorar otros mundos. Las uniones estables y los romances que se inicien estarán favorecidos pero deberán evitar perder la paciencia o situarse en lugares rígidos de exigencia hacia el otro.");
            Info2.setText("Poderoso y confiable, el Buey es capaz de marcar tendencia y nació para liderar. Lento y metódico. Nunca pierde de vista sus metas y por eso consigue lo que desea, con constancia y sin apuro. Su energía es interminable y es muy consciente de los detalles. Cree en hacer bien las cosas desde la primera vez. Obsesivo en lo que emprende, es tozudo, terco, responsable y moralista. Odia dejar las cosas a medias y la tranquilidad de sus reacciones abruma a cualquiera. Pacifista, sabio, maduro, organizador y líder, el Búfalo es un filósofo, un ser de gran espiritualidad. Solitario, le cuesta movilizarse, odia la improvisación y posee un gran sentido del humor. En su vida afectiva no es impulsivo, más bien cauteloso, pero su amor es profundo, eterno y leal. Práctico, inspirado pero con los pies en la tierra, es un excelente compañero de camino y una fuente de consejos sabios y sinceros. Su signo correspondiente en occidente es Capricornio. ");
        }
        if (Año.equals("1900")|Año.equals("1912")|Año.equals("1924")|Año.equals("1936")|Año.equals("1948")|Año.equals("1960")|Año.equals("1972")|Año.equals("1984")|Año.equals("1996")|Año.equals("2008")|Año.equals("2020"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.rata));
            Info.setText("Este año surgirán nuevas oportunidades pero deberán estar atentos al tomar decisiones ya que la energía del Gallo, signo opuesto y complementario del Gato, exigirá compromiso, enfoque y determinación. La intuición que tienen para captar el fondo de las situaciones, les ayudará enormemente este año y sabrán salir siempre de la mejor manera, caer siempre parados. Aprenderán mucho a través de las asociaciones y alianzas que establezcan, reconocerán sus verdaderos propósitos y necesidades y sabrán poner límites cuando sea necesario. Se definen situaciones en la pareja, que podrá afianzarse o terminar para siempre. Pasarán momentos de soledad, lo cual no será para nada malo, ya que hay una gran oportunidad de encontrar el amor verdadero este año.");
            Info2.setText("Tímido y atractivo, el Gato es muy popular entre sus amigos y seres queridos. Su naturaleza es protectora y compasiva con tendencia a idealizar sus relaciones. Es uno de los más sensibles del horóscopo y necesita bases afectivas sólidas para prosperar. En Oriente, se lo considera el signo más afortunado. Inspira gran respeto y en él se conjugan la armonía, la belleza, el magnetismo y el misterio. Su influencia en los demás es muy poderosa. Con una personalidad fascinante, adora vivir bien, elige siempre lo mejor y su presencia es plácida, reservada y sigilosa. Siempre dispuesto a ayudar, es diplomático y necesita tranquilidad, quietud y mucha seguridad para vivir. Los sobresaltos e inseguridades lo descolocan y bloquean. Tiene buen ojo para los negocios y posee una intuición prodigiosa que nunca le falla. Necesita un compañero o compañera que le brinde la paz que tanto anhela y si lo encuentra, será para siempre. Al igual que Piscis, signo análogo al Gato en el zodíaco occidental.");
        }
        if (Año.equals("1903")|Año.equals("1915")|Año.equals("1927")|Año.equals("1939")|Año.equals("1951")|Año.equals("1963")|Año.equals("1975")|Año.equals("1987")|Año.equals("1999")|Año.equals("2011")|Año.equals("2023"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.conejo));
            Info.setText("Este año surgirán nuevas oportunidades pero deberán estar atentos al tomar decisiones ya que la energía del Gallo, signo opuesto y complementario del Gato, exigirá compromiso, enfoque y determinación. La intuición que tienen para captar el fondo de las situaciones, les ayudará enormemente este año y sabrán salir siempre de la mejor manera, caer siempre parados. Aprenderán mucho a través de las asociaciones y alianzas que establezcan, reconocerán sus verdaderos propósitos y necesidades y sabrán poner límites cuando sea necesario. Se definen situaciones en la pareja, que podrá afianzarse o terminar para siempre. Pasarán momentos de soledad, lo cual no será para nada malo, ya que hay una gran oportunidad de encontrar el amor verdadero este año.");
            Info2.setText("Tímido y atractivo, el Gato es muy popular entre sus amigos y seres queridos. Su naturaleza es protectora y compasiva con tendencia a idealizar sus relaciones. Es uno de los más sensibles del horóscopo y necesita bases afectivas sólidas para prosperar. En Oriente, se lo considera el signo más afortunado. Inspira gran respeto y en él se conjugan la armonía, la belleza, el magnetismo y el misterio. Su influencia en los demás es muy poderosa. Con una personalidad fascinante, adora vivir bien, elige siempre lo mejor y su presencia es plácida, reservada y sigilosa. Siempre dispuesto a ayudar, es diplomático y necesita tranquilidad, quietud y mucha seguridad para vivir. Los sobresaltos e inseguridades lo descolocan y bloquean. Tiene buen ojo para los negocios y posee una intuición prodigiosa que nunca le falla. Necesita un compañero o compañera que le brinde la paz que tanto anhela y si lo encuentra, será para siempre. Al igual que Piscis, signo análogo al Gato en el zodíaco occidental.");
        }
        if (Año.equals("1904")|Año.equals("1916")|Año.equals("1928")|Año.equals("1940")|Año.equals("1952")|Año.equals("1964")|Año.equals("1976")|Año.equals("1988")|Año.equals("2000")|Año.equals("2012")|Año.equals("2024"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.dragon));
            Info.setText("Buen tiempo para aprender, estudiar, publicitar o promocionarse. El peligro estará en querer hacer muchas cosas al mismo tiempo y disgregarse. Deberán focalizar los esfuerzos y no dudar a la hora de tomar decisiones radicales. Habrá mucha actividad pero poco tiempo para disfrutar en casa, lo cual puede hacerles perder el buen humor. Será imprescindible disponer de una magnífica organización, planificar muy bien el tiempo y combinar el trabajo con las necesidades más espirituales. Necesitarán cultivar la paciencia y evitar cualquier situación conflictiva en las relacione. Es momento de hacer una evaluación y decidir ir más despacio.");
            Info2.setText("El Dragón es el signo más celebrado del Zodiaco Chino. Es poderoso y muy afortunado, de buen corazón y lleno de energía. Es un ser inteligente nacido con un carisma inagotable, lo que le garantiza influir en las acciones de quienes lo rodean y con frecuencia lo vuelve el centro de atención, sitio en el que ama estar. Del mismo modo que es afortunado con el dinero, es afortunado en el amor. Ganador nato, debe aprender a ser más flexible y tolerante para llegar a ser un gran líder. Es el único animal irreal y mitológico del Horóscopo Chino. En China se lo venera y respeta y es emblema de su cultura. Vive de una manera muy intensa y no soporta la monotonía, su seguridad en sí mismo lo hace capaz de construir un imperio y contagiar su entusiasmo a los demás. Nació para tener un destino especial, no es convencional, despierta grandes pasiones y jamás retrocede en sus decisiones. El signo análogo y de características similares es Aries. ");
        }
        if (Año.equals("1905")|Año.equals("1917")|Año.equals("1929")|Año.equals("1941")|Año.equals("1953")|Año.equals("1965")|Año.equals("1977")|Año.equals("1989")|Año.equals("2001")|Año.equals("2013")|Año.equals("2025"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.serpiente));
            Info.setText("2017 será un año de grandes logros para la Serpiente. Aparecerán oportunidades, estarán motivados y tendrán buen juicio para poner en marcha planes bien concretos. La habilidad y majestuosidad que despliega el Gallo de fuego, la Serpiente la capitalizará en el manejo de las relaciones públicas, se abrirán nuevas puertas. Las artistas del signo obtendrán grandes logros y ganancias a través de sus obras. Será necesario ser constante para alcanzar los objetivos que realmente importan. Será un año de enamoramiento y conquista, donde disfrutarán a pleno de la sensualidad y el misterio que los caracteriza. En la pareja habrá buena convivencia si evitan los excesos y los celos.");
            Info2.setText("La Serpiente es el signo más seductor del Zodiaco Chino. Siempre bien recibida, la Serpiente es sociable aunque introvertida; también posee intuición y cuenta con una aptitud natural para los negocios y, aunque es posible que no considere al dinero como muy importante, su suerte y la tendencia a no gastar más de lo necesario aseguran que tendrá más dinero del que requiere. En Oriente su imagen se encuentra en la pintura, la literatura y toda manifestación artística como símbolo del más exquisito refinamiento, sabiduría y belleza. En general tiene una naturaleza reservada y una mente analítica que hace que los retos intelectuales le sean más atractivos que las actividades físicas. Su claridad e inteligencia profunda le son indispensables para nutrirse y desarrollarse. Con una gran capacidad de lucha, tesón y perseverancia, es muy precavido y con un gran sentido práctico a la vez que estético. Constante y responsable, exclusivista, celoso y posesivo, necesita tener el control de las situaciones y puede volverse obsesivo y desconfiado. Características que comparte con su signo análogo: Tauro.");
        }
        if (Año.equals("1906")|Año.equals("1918")|Año.equals("1930")|Año.equals("1942")|Año.equals("1954")|Año.equals("1966")|Año.equals("1978")|Año.equals("1990")|Año.equals("2002")|Año.equals("2014")|Año.equals("2026"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.caballo));
            Info.setText("El año del Gallo se presenta desafiante para el Caballo que tendrá que detener su paso, poner orden y evitar la comodidad. No será un año del todo fácil y las contradicciones estarán a la orden del día. Pero tendrán la oportunidad de ser más conscientes de las propias debilidades y contar con las herramientas para transformarlas. Si lo logran, alcanzarán gran prosperidad en cada ámbito de vida. Suavizar el carácter, enfocar y canalizar positivamente las energías será preciso para lograr bienestar y armonía en las relaciones. Para la vida en pareja es un año de pruebas en donde el diálogo será la clave para encontrar un punto de equilibrio en la relación.");
            Info2.setText("El Caballo posee un espíritu libre que lo hace el trotamundo del Zodiaco Chino. Necesita independencia y libertad, está cargado de energía y se mueve constantemente de una actividad a otra. Es bueno con el dinero, y por supuesto tiene una gran pasión por los viajes. Es el signo más pintoresco del Horóscopo Chino. Su sola presencia es llamativa porque es brioso, bello y fuerte. Con un carisma irresistible, tiene un carácter inquieto, ciclotímico y muchas veces es imprevisible en su conducta. Habilidoso en el arte de la seducción, le agrada alardear frente a las multitudes. A pesar de la fortaleza de su naturaleza, muchas veces se sienten menos que quienes lo rodean. El Caballo es bueno para trabajar en equipo y cuando una causa lo entusiasma pondrá su talento y esfuerzo para concretarla. Rebelde, anticonvencional e inconsciente, le agrada generar cambios, estar siempre informado, comunicarse e interactuar. Si sabe encauzar sus energías podrá lograr todo lo que se proponga en la vida. El signo análogo al Caballo en el zodíaco occidental es Géminis.");
        }
        if (Año.equals("1907")|Año.equals("1919")|Año.equals("1931")|Año.equals("1943")|Año.equals("1955")|Año.equals("1967")|Año.equals("1979")|Año.equals("1991")|Año.equals("2003")|Año.equals("2015")|Año.equals("2027"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.cabra));
            Info.setText("Se sentirán optimistas y lograrán una posición estable y segura. Deberán esforzarse pero alcanzarán grandes metas ya que contarán con una importante claridad mental para actuar en el momento oportuno. Habrá novedades en asuntos inmobiliarios y todo lo relacionado con la vivienda. Reparaciones o renovaciones dentro del hogar, podrán contar con mayor comodidad y confort. Un cambio importante en la forma de comunicarse les permitirá establecer vínculos más profundos. Podrán viajar, mudarse y recibir la llegada de un gran amor. En la pareja, deberán esforzarse por escuchar al otro, comprender sus necesidades y no querer imponer siempre sus puntos de vista.");
            Info2.setText("La Cabra es soñadora, un espíritu creativo que siempre necesita más tiempo para explorar su interior. Se siente más a gusto cuando está inmersa en la profundidad de su propio ser. Para ser feliz, la mente de la Cabra necesita ser libre para vagar por donde desee. Naturalmente artística e inventiva, no persigue la riqueza material y confía en su imaginación para enriquecer su vida. Es el signo más delicado del Horóscopo Chino. Muy sensible, aparentemente frágil, solidaria y generosa. Necesita seguridad y busca rodearse de gente que la reafirme como persona. Nació para ayudar y su gran corazón y amor son el vehículo para manifestar su espíritu protectivo y de sacrificio. Le cuesta estar sola y es uno de los signos más románticos. Ejecutiva por excelencia, posee gran sentido del valor de las cosas y atrae el dinero. Adora el mundo esotérico, la astrología y la parapsicología. Sentimental, emotiva, susceptible y reservada, presenta una necesidad imperiosa de autoprotección. Características similares a su signo análogo: Cáncer.");
        }
        if (Año.equals("1908")|Año.equals("1920")|Año.equals("1932")|Año.equals("1944")|Año.equals("1956")|Año.equals("1968")|Año.equals("1980")|Año.equals("1992")|Año.equals("2004")|Año.equals("2016")|Año.equals("2028"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.mono));
            Info.setText("Para quienes han nacido en un año Mono, será una etapa de concreciones, ideal para desarrollar y concluir proyectos iniciados el año anterior. Durante 2016, el año del Mono, han comenzado una nueva etapa, un nuevo ciclo de 12 años. El Gallo les pedirá ahora concreciones materiales, responsabilidad y empeño. Los cambios se darán en la manera de administrar las energías y el tiempo, adaptarse a ciertas rutinas será la clave. En el amor, la tendencia será a establecer un compromiso estable y renovarán los votos en la pareja. Si estás sola, podrán iniciar un romance intenso con alguien en quien encuentren comprensión, tranquilidad y confianza.");
            Info2.setText("Encantador y lleno de energía, el Mono es el más alegre del Zodiaco Chino. Tiene un apetito insaciable por diversión y actividad y es fácil para él pasar un buen rato entre cualquier multitud. Es optimista, ingenioso y poseen una mente muy aguda, su inteligencia le permite realizar tareas complejas con gran facilidad. Nació para alegrar a la humanidad y transmitir su peculiar visión de la vida. Es el signo más lúdico, detesta la rutina, los esquemas, los convencionalismos y las instituciones. Representa la libertad, la creatividad y no le teme a nada: todo lo que se propone, lo consigue. Curioso, se interesa por varias cosas al mismo tiempo y lo que más le cuesta es la disciplina. Adora el lujo, el confort y vivir espléndidamente aunque puede caer en el egocentrismo o un desmedido orgullo. Posee un carácter fuerte y dominante pero a la vez es sentimental y apasionado. Llamativo y con deseos de destacarse, combinado con una gracia natural que lo convierte en uno de los signos más atractivos del Zodiaco. Su humor muchas veces lo salva de las situaciones más difíciles de la vida. Características que comparte con su análogo Leo en el zodiaco occidental.");
        }
        if (Año.equals("1909")|Año.equals("1921")|Año.equals("1933")|Año.equals("1945")|Año.equals("1957")|Año.equals("1969")|Año.equals("1981")|Año.equals("1993")|Año.equals("2005")|Año.equals("2017")|Año.equals("2029"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.gallo));
            Info.setText("La energía del fuego será la encargada de dar vida a un año intenso y lleno de positivismo para todos los Gallo. Con una actitud más práctica y decidida, sentirán que nada está fuera de su alcance. Sabrán administrar su intensa energía con más inteligencia y tendrán la posibilidad de conocer gente influyente que los beneficiará en su profesión. Crecerán las responsabilidades, pero hasta las cosas más complicadas serán fáciles de realizar. El desafío estará en saber aceptar los buenos consejos de gente más experimentada y aprender a delegar cuando las situaciones los desborden. Brillarán con encanto despertando grandes pasiones. Las parejas se encenderán, pudiendo reavivar la relación o bien poniéndola en crisis, dependerá de cómo equilibren sus emociones. Los Gallos solitarios tendrán grandes oportunidades de nuevas conquistas.");
            Info2.setText("Ingenioso y avispado, el Gallo es pragmático y prefiere no tomar ningún riesgo. Gran observador de lo que ocurre a su alrededor, nada se le escapa. Su imaginación y fantasía, unidas a su sentido práctico, produce una personalidad llena de matices. Extravagante y avasallante posee mucha potencia y es de sostener arraigados ideales que defiende con su vida. Honesto, perfeccionista y, como signo que cumple con su palabra, le gusta tener todo bajo control. Su apariencia personal es muy importante y es extremadamente prolijo y pulcro. Muy trabajador, le gusta estar ocupado y es capaz de mucha disciplina y determinación. Valiente, luchador y sociable, su vida nunca es aburrida. No le teme al sacrificio y posee una personalidad racional, una gran capacidad de análisis y mucha lógica. Es ordenado, metódico y responsable, destaca por su eficiencia y seriedad. Detallista y obsesionado con la perfección, en el amor es fiel y posesivo y quiere tener siempre el control de su casa, su pareja y sus hijos. Su correlativo en el horóscopo occidental es Virgo.");
        }
        if (Año.equals("1910")|Año.equals("1922")|Año.equals("1934")|Año.equals("1946")|Año.equals("1958")|Año.equals("1970")|Año.equals("1982")|Año.equals("1994")|Año.equals("2006")|Año.equals("2018")|Año.equals("2030"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.perro));
            Info.setText("Al comenzar el año deberán ir sin apresuramientos. No será conveniente realizar cambios profundos ni definitivos, sino más bien esperar para tomar grandes decisiones. En 2017 la independencia será su foco pero deberán tener especial cuidado con los conflictos a nivel laboral, con perder la paciencia. Trabajarán para labrarse un buen futuro profesional, del cual recogerá los frutos en 2018, que será el año del Perro. Será un año excitante y no todo serán dificultades: obtendrán algunos triunfos importantes. Este año Gallo, deberán ser más firmes en sus puntos de vista y no dejarse llevar con facilidad por las opiniones ajenas. Aceptación y mayor independencia serán la clave para vivir en armonía el amor y la vida en pareja.");
            Info2.setText("Fiel, confiable y con un fuerte sentido de la ética, es el animal más noble del Horóscopo Chino. Amigo fiel y excepcional para escuchar, es un guerrero que combatirá contra la injusticia y se alineará con los desposeídos en cualquier momento y lugar. Suele ser amable y amistoso, aunque en situaciones angustiantes es capaz de mostrar sus incisivos caninos. Su fuerte sentido de la justicia lo impulsa a hacer siempre lo correcto y a defender las causas justas. Tiene mucha entereza, solidaridad y es estoico como un soldado. Busca referentes y muchas veces piensa más en el prójimo que en sí mismo, por lo cual es mejor custodia de la vida ajena que de la propia. Como el animalito del Horóscopo Chino, está siempre alerta y tiene un radar para detectar el peligro, la traición y la mala onda. Es elegante, refinado, artístico y con un exquisito buen gusto. Su signo análogo en el zodíaco occidental es Libra.");
        }
        if (Año.equals("1911")|Año.equals("1923")|Año.equals("1935")|Año.equals("1947")|Año.equals("1959")|Año.equals("1971")|Año.equals("1983")|Año.equals("1995")|Año.equals("2007")|Año.equals("2019")|Año.equals("2031"))
        {
            Imagen.setImageDrawable(getDrawable(R.drawable.chancho));
            Info.setText("Será un buen año para el Jabalí, el Gallo lo sabrá guiar por el camino de su propia evolución. Su energía de fuego los invitará a tomar el control de sus vidas y a actuar con energía y decisión. El trabajo en equipo, la vida social y los amigos ocuparán un lugar preponderante. Este año se movilizan viejos sueños, se aclaran las ideas y muchos serán los que encuentren el verdadero amor. El autoconocimiento y la búsqueda interior serán la clave para desprenderse de todo aquello que impide el avance. Más libres y conscientes, tendrán la posibilidad de ver florecer su vida de relación. Vivirán el amor a pleno con momentos de gran sensualidad, romanticismo y mucho placer.");
            Info2.setText("El Chancho fue el último en llegar a ver al Buda, pues su manera de asimilar los hechos nada tiene que ver con el resto de la gente. Posee una gran fuerza interior y su vida tiene una profunda coherencia. Con una personalidad bien definida, pero llena de matices, el Chancho nunca pasa inadvertido, es un eterno aprendiz y posee una actitud ingenua y generosa ante la vida. Su experiencia lo guía, y aunque a veces cometa errores, sabe enriquecerse y evolucionar. Sensual y lujurioso por naturaleza, adora las cosas más finas y mejores de la vida. Se preocupa profundamente por sus amigos y su familia y llegará a grandes extremos por mantenerlos felices y con bienestar: no considera que ayudar sea un deber sino un placer. En todo lo que dice y hace hay un verdadero compromiso, es brillante, talentoso y muy trabajador. No le gustan los cambios bruscos, le agrada el dinero y es el signo más sensual del Horóscopo Chino. Lúcido, realista pero también misterioso y apasionado, es enérgico y nada le es indiferente, nada le da igual. Aunque con los pies en la tierra, posee una intuición extraordinaria, al igual que Escorpio, su signo análogo en el horóscopo occidental.");
        }



    }
}
